services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=/data/db.sqlite3
      - COMMIT_HASH=YFTCKJGHVJHFJYFCKYC
    volumes:
      - backend_data:/data
    develop:
      watch:
        - action: sync+restart
          path: ./backend/app
          target: /code/app
        - action: rebuild
          path: ./backend/requirements.txt
          target: /code/requirements.txt
        - action: rebuild
          path: ./backend/Dockerfile
          target: /code/Dockerfile

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://localhost:8000/api
      - COMMIT_HASH=YFTCKJGHVJHFJYFCKYC
      - ENV=development
    develop:
      watch:
        - action: rebuild
          path: ./frontend
          target: /app

volumes:
  backend_data:
