services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=/data/db.sqlite3
      - COMMIT_HASH=dev
    volumes:
      - backend_data:/data

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://localhost:8000/api
      - COMMIT_HASH=dev
      - ENV=development

volumes:
  backend_data:
