services:
  # Site Principal (par exemple, `web-audit-per2024`)
  main-entry:
    build: ./main-entry
    container_name: main-entry
    restart: always
    networks:
      main-network:
        ipv4_address: 192.168.0.2
    ports:
      - "8080:80"

  # Site Vulnérable (par exemple, `vulnerable-site-1`)
  vulnerable-site-1:
    build: ./vulnerable-site-1
    container_name: vulnerable-site-1
    restart: always
    networks:
      vuln-network:
        ipv4_address: 192.168.1.2
    ports:
      - "8081:80"


  # Service d'Analyse (par exemple, `web-analyzer`)
  web-analyzer:
    build: ./web-analyzer
    container_name: web-analyzer
    restart: always
    networks:
      main-network:
        ipv4_address: 192.168.0.3
    expose:
      - "5000"  # Port interne pour la communication avec main-entry

networks:
  # Réseau pour le serveur web principal
  main-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24

  # Réseau pour le site vulnérable
  vuln-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
